'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {adminSupabase} from '@/app/lib/browser-supabase';
type Promoter={id:string;full_name:string;referral_code:string;phone:string;city:string;status:string;created_at:string};
type Lead={id:string;promoter_id:string;business_name:string;category:string;contact_name:string;contact_phone:string;city:string;status:string;commission_paise:number;created_at:string};
const money=(p:number)=>'₹'+(p/100).toLocaleString('en-IN',{minimumFractionDigits:2});
export default function FieldPromoterAdmin(){const router=useRouter();const [promoters,setPromoters]=useState<Promoter[]>([]),[leads,setLeads]=useState<Lead[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
const token=async()=>{const {data}=await adminSupabase().auth.getSession();return data.session?.access_token||''};
const load=useCallback(async()=>{setLoading(true);try{const t=await token();if(!t){router.replace('/admin/login');return}const r=await fetch('/api/admin/field-promoters',{headers:{Authorization:'Bearer '+t},cache:'no-store'});if(r.status===401||r.status===403){router.replace('/admin/login');return}const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load');setPromoters(d.promoters||[]);setLeads(d.leads||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load')}finally{setLoading(false)}},[router]);
useEffect(()=>{void load()},[load]);
const stats=useMemo(()=>({approved:promoters.filter(x=>x.status==='APPROVED').length,pending:leads.filter(x=>x.status==='PENDING').length,verified:leads.filter(x=>x.status==='VERIFIED').length,earned:leads.reduce((a,x)=>a+(x.status==='VERIFIED'?x.commission_paise:0),0)}),[promoters,leads]);
async function change(kind:'promoter'|'lead',id:string,status:string){if(busy||!window.confirm('Confirm '+status.toLowerCase()+'? Verify supporting evidence before approving.'))return;setBusy(id);setNotice('');try{const t=await token();const r=await fetch('/api/admin/field-promoters',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:JSON.stringify({kind,id,status})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Update failed');setNotice('Updated successfully');await load()}catch(e){setError(e instanceof Error?e.message:'Update failed')}finally{setBusy('')}}
return <main className="min-h-screen bg-slate-50 p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-6xl"><Link href="/admin/dashboard" className="text-sm font-bold text-[#075E45]">← Admin dashboard</Link><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Field promoter management</h1><p className="mt-2 text-sm text-slate-600">Review applications, approve genuine leads and calculate commissions. No automatic payouts.</p></div><button onClick={()=>void load()} className="rounded-xl border bg-white px-4 py-2 font-bold">Refresh</button></div>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{notice&&<p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-emerald-800">{notice}</p>}
<div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4">{[['Approved promoters',stats.approved],['Pending leads',stats.pending],['Verified leads',stats.verified],['Approved commission',money(stats.earned)]].map(([label,value])=><div key={label} className="rounded-2xl border bg-white p-4"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>)}</div>
{loading?<p className="mt-8">Loading…</p>:<><section className="mt-8 rounded-2xl border bg-white p-4"><h2 className="text-xl font-black">Promoter applications</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[750px] text-left text-sm"><thead><tr className="border-b text-slate-500">{['Promoter','Contact','City','Referral code','Status','Review'].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{promoters.map(p=><tr key={p.id} className="border-b"><td className="p-3 font-bold">{p.full_name}</td><td className="p-3">{p.phone}</td><td className="p-3">{p.city}</td><td className="p-3 font-mono">{p.referral_code}</td><td className="p-3">{p.status}</td><td className="p-3">{p.status==='PENDING'?<button disabled={!!busy} onClick={()=>void change('promoter',p.id,'APPROVED')} className="rounded-lg bg-emerald-700 px-3 py-2 font-bold text-white">Approve</button>:p.status==='APPROVED'?<button disabled={!!busy} onClick={()=>void change('promoter',p.id,'SUSPENDED')} className="rounded-lg bg-amber-100 px-3 py-2 font-bold">Suspend</button>:<button disabled={!!busy} onClick={()=>void change('promoter',p.id,'APPROVED')} className="rounded-lg bg-emerald-100 px-3 py-2 font-bold">Restore</button>}</td></tr>)}</tbody></table>{!promoters.length&&<p className="p-4 text-sm text-slate-500">No applications yet.</p>}</div></section>
<section className="mt-6 rounded-2xl border bg-white p-4"><h2 className="text-xl font-black">Business onboarding review</h2><p className="mt-1 text-xs text-slate-500">Verify the business owner, genuine onboarding and applicable driver compliance before approval. Approval records category-based commission; it does not pay the promoter.</p><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead><tr className="border-b text-slate-500">{['Business','Category','Contact','Promoter','Status','Commission','Review'].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{leads.map(l=><tr key={l.id} className="border-b"><td className="p-3 font-bold">{l.business_name}<span className="block text-xs font-normal">{l.city}</span></td><td className="p-3">{l.category}</td><td className="p-3">{l.contact_name}<span className="block">{l.contact_phone}</span></td><td className="p-3">{promoters.find(p=>p.id===l.promoter_id)?.referral_code||'Unknown'}</td><td className="p-3">{l.status}</td><td className="p-3">{money(l.commission_paise)}</td><td className="p-3">{l.status==='PENDING'&&<div className="flex gap-2"><button disabled={!!busy} onClick={()=>void change('lead',l.id,'VERIFIED')} className="rounded-lg bg-emerald-700 px-3 py-2 font-bold text-white">Verify</button><button disabled={!!busy} onClick={()=>void change('lead',l.id,'REJECTED')} className="rounded-lg bg-red-50 px-3 py-2 font-bold text-red-800">Reject</button></div>}</td></tr>)}</tbody></table>{!leads.length&&<p className="p-4 text-sm text-slate-500">No leads yet.</p>}</div></section></>}</div></main>}
