plugins {
    id 'com.android.application'
}

android {
    namespace 'in.zeshu.test'
    compileSdk 35

    defaultConfig {
        applicationId 'in.zeshu.test'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '0.1-staging'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
