import Link from "next/link";
import ProfessionalEnquiryForm from "@/app/components/ProfessionalEnquiryForm";
import { ArrowRight, Building2, Home, MapPin, Paintbrush, PanelsTopLeft, Wrench } from "lucide-react";

export const metadata={title:"Zeshu Interiors | Design & Renovation Quotes",description:"Explore interior design, kitchen, wardrobe, painting and renovation services through Zeshu."};
const categories=[["Full interiors",Home],["Modular kitchens",PanelsTopLeft],["Painting & finishes",Paintbrush],["Renovation",Wrench]];
export default function InteriorsPage(){return <main data-zeshu-experience="glossy" className="zeshu-experience min-h-screen bg-amber-50/40"><section className="mx-auto max-w-6xl px-4 py-8 md:py-12">
<Link href="/professional-services" className="text-sm font-black text-[#075E45]">← Zeshu Services</Link>
<div className="zeshu-gloss-hero mt-5 rounded-3xl bg-[linear-gradient(135deg,#2f493d,#5d765f)] p-6 text-white md:p-10"><p className="text-xs font-black uppercase tracking-[.16em] text-white/75">Zeshu Interiors</p><h1 className="mt-2 max-w-3xl text-3xl font-black md:text-5xl">From an empty room to a clear interior plan.</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-white/85 md:text-base">Share the type of space, approximate area, location, requirements and budget range. Zeshu can connect quote requests to suitable professionals as real coverage is onboarded.</p></div>
<div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4">{categories.map(([name,Icon])=><div key={String(name)} className="zeshu-gloss-card rounded-2xl border border-amber-100 bg-white p-4">{typeof Icon!=="string"&&<Icon className="text-[#075E45]" size={22}/>}<h2 className="mt-3 text-sm font-black">{name as string}</h2></div>)}</div>
<section className="zeshu-gloss-card mt-6 rounded-3xl border bg-white p-6"><Building2 className="text-[#075E45]"/><h2 className="mt-3 text-2xl font-black">Request interior quotes</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">For homes, shops and offices. The first release collects genuine enquiries while professionals are onboarded; it does not invent project prices or provider availability.</p><ProfessionalEnquiryForm service="INTERIORS"/><div className="mt-5 flex flex-wrap gap-3"><Link href="/help" className="inline-flex items-center gap-2 rounded-xl bg-[#075E45] px-5 py-3 text-sm font-black text-white">Contact Zeshu about your project <ArrowRight size={16}/></Link><Link href="/partners" className="inline-flex items-center gap-2 rounded-xl border px-5 py-3 text-sm font-black text-slate-800">Are you an interior professional?</Link></div></section>
<p className="mt-5 text-xs font-semibold text-slate-500"><MapPin size={14} className="mr-1 inline"/>Coverage is shown only where Zeshu has onboarded service providers.</p>
</section></main>}
