'use client';
import { useState, type FormEvent } from 'react';
export default function ProfessionalEnquiryForm({service}:{service:'WEDDING'|'INTERIORS'}) {
 const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setStatus('');const form=e.currentTarget;const data=Object.fromEntries(new FormData(form).entries());try{const response=await fetch('/api/professional-services/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,service_type:service,consent:data.consent==='on'})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not submit');setStatus('Thank you. Your enquiry was received. Zeshu will contact you if suitable professionals are available.');form.reset();}catch(err){setStatus(err instanceof Error?err.message:'Please try again.');}finally{setBusy(false)}}
 const fields=[['customer_name','Your name','text'],['contact_phone','Mobile number','tel'],['city','Project city / location','text']];
 return <form onSubmit={submit} className="mt-5 grid gap-4" aria-label="Request a professional service quote">
 <div className="grid gap-3 sm:grid-cols-2">{fields.map(([name,label,type])=><label key={name} className="block text-sm font-semibold text-slate-700">{label}<input required minLength={name==='contact_phone'?10:2} maxLength={name==='contact_phone'?20:100} name={name} type={type} className="mt-1 block w-full rounded-xl border border-slate-300 p-3 text-base" /></label>)}
 <label className="block text-sm font-semibold text-slate-700">Budget range<select name="budget_range" required defaultValue="" className="mt-1 block w-full rounded-xl border border-slate-300 p-3 text-base"><option value="" disabled>Select a range</option>{(service==='WEDDING'?['Under ₹1 lakh','₹1–5 lakh','₹5–15 lakh','₹15 lakh+','Discuss with provider']:['Under ₹50,000','₹50,000–2 lakh','₹2–5 lakh','₹5 lakh+','Discuss with provider']).map(v=><option key={v}>{v}</option>)}</select></label>
 <label className="block text-sm font-semibold text-slate-700">{service==='WEDDING'?'Event date (optional)':'Preferred start date (optional)'}<input name="requested_date" type="date" className="mt-1 block w-full rounded-xl border border-slate-300 p-3 text-base"/></label></div>
 <label className="block text-sm font-semibold text-slate-700">Tell us what you need<textarea name="project_details" required minLength={10} maxLength={2000} rows={4} placeholder={service==='WEDDING'?'Guest count, venue, services needed…':'Property type, approximate area, rooms and requirements…'} className="mt-1 block w-full rounded-xl border border-slate-300 p-3 text-base"/></label>
 <label className="hidden" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label>
 <label className="flex items-start gap-2 text-xs text-slate-600"><input required type="checkbox" name="consent" className="mt-1"/>I agree to Zeshu contacting me about this enquiry. Submission does not guarantee a quote or booking.</label>
 <button disabled={busy} className="rounded-xl bg-[#075E45] px-5 py-3 font-black text-white disabled:opacity-60">{busy?'Submitting…':'Request a quote'}</button><p role="status" className="text-sm font-semibold text-slate-700">{status}</p></form>;
}
