import Link from "next/link";
import { ArrowRight, CalendarDays, Camera, ChefHat, Flower2, MapPin, PartyPopper, Sparkles } from "lucide-react";
export const metadata={title:"Zeshu Weddings | Find Wedding Professionals",description:"Discover wedding planners and vendors and request quotes through Zeshu."};
const cats=[["Wedding planners",PartyPopper],["Venues",MapPin],["Catering",ChefHat],["Décor",Flower2],["Photography & video",Camera],["Makeup & mehendi",Sparkles]];
export default function Weddings(){return <main className="mx-auto min-h-screen max-w-6xl px-4 py-8 md:py-12">
 <p className="text-xs font-black uppercase tracking-[.16em] text-[#075E45]">Zeshu Weddings</p><h1 className="mt-2 max-w-3xl text-3xl font-black tracking-tight md:text-5xl">Plan the celebration. Compare the professionals.</h1>
 <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Start with your city, date, guest count and services needed. Zeshu will only present professionals for areas they actually serve.</p>
 <div className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-3">{cats.map(([name,Icon])=>{const I=Icon as typeof PartyPopper;return <div key={name as string} className="rounded-2xl border border-slate-200 bg-white p-4"><I className="text-[#075E45]" size={22}/><h2 className="mt-3 text-sm font-black">{name as string}</h2></div>})}</div>
 <section className="mt-7 rounded-3xl bg-[#075E45] p-6 text-white md:p-8"><CalendarDays size={26}/><h2 className="mt-3 text-2xl font-black">Request wedding professionals</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/85">Provider onboarding is in progress. Until live matching is connected, customer requirements can be handled through Zeshu Customer Service without pretending a vendor is available.</p><Link href="/help" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-black text-slate-900">Contact Customer Service <ArrowRight size={16}/></Link></section>
 </main>}