import {NextResponse} from 'next/server';import {createClient} from '@supabase/supabase-js';
export const runtime='nodejs';
async function context(request:Request){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY,anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,header=request.headers.get('authorization')||'';if(!url||!key||!anon||!header.startsWith('Bearer '))return null;const auth=createClient(url,anon,{auth:{persistSession:false}});const {data}=await auth.auth.getUser(header.slice(7));if(!data.user)return null;const db=createClient(url,key,{auth:{persistSession:false}});const {data:admin}=await db.from('admin_roles').select('user_id').eq('user_id',data.user.id).eq('role','admin').maybeSingle();return admin?db:null}
export async function GET(request:Request){const db=await context(request);if(!db)return NextResponse.json({error:'Admin authorization required'},{status:403});const [promoters,leads,settlements]=await Promise.all([db.from('field_promoters').select('id,referral_code,full_name,phone,city,status,created_at').order('created_at',{ascending:false}).limit(300),db.from('field_promoter_leads').select('id,promoter_id,business_name,category,contact_name,contact_phone,city,notes,status,commission_paise,created_at').order('created_at',{ascending:false}).limit(500),db.from('field_promoter_settlements').select('id,promoter_id,amount_paise,reference,notes,created_at').order('created_at',{ascending:false}).limit(500)]);if(promoters.error||leads.error||settlements.error)return NextResponse.json({error:'Data temporarily unavailable'},{status:503});return NextResponse.json({promoters:promoters.data,leads:leads.data,settlements:settlements.data})}
export async function PATCH(request:Request){const db=await context(request);if(!db)return NextResponse.json({error:'Admin authorization required'},{status:403});let body:Record<string,unknown>;try{body=await request.json()}catch{return NextResponse.json({error:'Invalid input'},{status:400})}const id=typeof body.id==='string'?body.id:'';if(!/^[a-f0-9-]{36}$/.test(id))return NextResponse.json({error:'Invalid record'},{status:400});
if(body.kind==='promoter'&&['APPROVED','SUSPENDED'].includes(String(body.status))){const {error}=await db.from('field_promoters').update({status:body.status}).eq('id',id);return error?NextResponse.json({error:'Update failed'},{status:503}):NextResponse.json({ok:true})}
if(body.kind==='lead'&&['VERIFIED','REJECTED'].includes(String(body.status))){const {data:lead}=await db.from('field_promoter_leads').select('id,status,category').eq('id',id).maybeSingle();if(!lead||lead.status!=='PENDING')return NextResponse.json({error:'Lead already processed or missing'},{status:409});const rates:Record<string,number>={'Grocery / retail':2000,'Restaurant / bakery':2500,'Clothing / footwear':2000,'Auto driver':3000,'Cab driver':4000,'Delivery / courier':2500,'Wedding professional':4000,'Interior designer':4000,'Home service professional':2500,'Other':2000};const {error}=await db.from('field_promoter_leads').update({status:body.status,commission_paise:body.status==='VERIFIED'?(rates[lead.category]||0):0}).eq('id',id).eq('status','PENDING');return error?NextResponse.json({error:'Update failed'},{status:503}):NextResponse.json({ok:true})}return NextResponse.json({error:'Unsupported change'},{status:400})}

export async function POST(request:Request){const db=await context(request);if(!db)return NextResponse.json({error:'Admin authorization required'},{status:403});let body:Record<string,unknown>;try{body=await request.json()}catch{return NextResponse.json({error:'Invalid request'},{status:400})}
const promoter_id=typeof body.promoter_id==='string'?body.promoter_id:'',reference=typeof body.reference==='string'?body.reference.trim():'',notes=typeof body.notes==='string'?body.notes.trim().slice(0,1000):'',amount_paise=body.amount_paise;
if(!/^[0-9a-f-]{36}$/i.test(promoter_id)||typeof amount_paise!=='number'||!Number.isSafeInteger(amount_paise)||amount_paise<=0||reference.length<5||reference.length>120||body.confirm_paid!==true)return NextResponse.json({error:'A verified payment reference, amount and explicit paid confirmation are required.'},{status:400});
const {data,error}=await db.rpc('record_field_promoter_settlement',{p_promoter_id:promoter_id,p_amount_paise:amount_paise,p_reference:reference,p_notes:notes});
if(error)return NextResponse.json({error:error.message.includes('duplicate key')?'This payment reference is already recorded.':'Settlement rejected: check approved balance and payment reference.'},{status:409});
return NextResponse.json({ok:true,settlement_id:data},{status:201})}
